export enum LeadStatus {
  FORM_SUBMITTED = "FORM_SUBMITTED",
  CALL_SCHEDULED = "CALL_SCHEDULED",
  CALL_ATTENDED = "CALL_ATTENDED",
  CALL_SCHEDULED_NO_SHOW = "CALL_SCHEDULED_NO_SHOW",
  CALL_ATTENDED_NO_PURCHASE = "CALL_ATTENDED_NO_PURCHASE",
  PURCHASED = "PURCHASED",
  COURSE_COMPLETED = "COURSE_COMPLETED",
}

export enum BudgetRange {
  RANGE_500_1000 = "$500-$1000",
  RANGE_1000_2000 = "$1000-$2000",
  RANGE_2000_5000 = "$2000-$5000",
}

export enum EmailFlowStatus {
  ACTIVE = "ACTIVE",
  PAUSED = "PAUSED",
  COMPLETED = "COMPLETED",
  UNSUBSCRIBED = "UNSUBSCRIBED",
}

export enum CurrentEmailFlow {
  NONE = "NONE",
  FORM_NO_CALL = "FORM_NO_CALL",
  CALL_REMINDERS = "CALL_REMINDERS",
  NO_SHOW = "NO_SHOW",
  NURTURE = "NURTURE",
  REFERRAL = "REFERRAL",
}
