export enum EmailType {
  FORM_FOLLOWUP_1 = "FORM_FOLLOWUP_1",
  FORM_FOLLOWUP_2 = "FORM_FOLLOWUP_2",
  CALL_CONFIRMATION = "CALL_CONFIRMATION",
  CALL_REMINDER_24H = "CALL_REMINDER_24H",
  CALL_REMINDER_2H = "CALL_REMINDER_2H",
  NO_SHOW_FOLLOWUP = "NO_SHOW_FOLLOWUP",
  NURTURE_1 = "NURTURE_1",
  NURTURE_2 = "NURTURE_2",
  NURTURE_3 = "NURTURE_3",
  NURTURE_MONTHLY_1 = "NURTURE_MONTHLY_1",
  NURTURE_MONTHLY_2 = "NURTURE_MONTHLY_2",
  REFERRAL_FEEDBACK = "REFERRAL_FEEDBACK",
  REFERRAL_PROGRAM = "REFERRAL_PROGRAM",
}

export enum EmailStatus {
  PENDING = "PENDING",
  SENT = "SENT",
  FAILED = "FAILED",
}
